{% set version = "0.12.0" %}

package:
  name: range-v3
  version: {{ version }}

source:
  url: https://github.com/ericniebler/range-v3/archive/refs/tags/{{ version }}.tar.gz
  sha256: 015adb2300a98edfceaf0725beec3337f542af4915cec4d0b89fa0886f4ba9cb

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                # [unix]

test:
  commands:
    - test -f $PREFIX/include/range/v3/all.hpp                             # [unix]
    - if not exist %PREFIX%\\Library\\include\\range\\v3\\all.hpp exit 1   # [win]

about:
  home: https://github.com/ericniebler/range-v3
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Range library for C++14/17/20, basis for C++20's std::ranges

extra:
  recipe-maintainers:
    - bluescarni
